name: Generate Keystore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Key
        run: |
          keytool -genkey -v -keystore nettumi.keystore -alias nettumi_alias -keyalg RSA -keysize 2048 -validity 10000 -storepass "Nettumi@123" -keypass "Nettumi@123" -dname "CN=Nettumi, OU=IT, O=Nettumi, L=Dhaka, S=Dhaka, C=BD"
      
      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: nettumi-keystore
          path: nettumi.keystore
